// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9zKc2SAFjyOxGnAHoSwQcS5ShhIx3RDQ',
    appId: '1:59810689802:web:63a702692689f61963c0f3',
    messagingSenderId: '59810689802',
    projectId: 'signin-3d778',
    authDomain: 'signin-3d778.firebaseapp.com',
    storageBucket: 'signin-3d778.firebasestorage.app',
    measurementId: 'G-D2WNN2YZV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuOH4Kw8nnUzE1KGmB-xxslgP2r7scTSs',
    appId: '1:59810689802:android:43d16b16cb950df863c0f3',
    messagingSenderId: '59810689802',
    projectId: 'signin-3d778',
    storageBucket: 'signin-3d778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zrxaoBMCqqwilDUrMQjTPRa_2D2qyBI',
    appId: '1:59810689802:ios:b4a3b10a723f256963c0f3',
    messagingSenderId: '59810689802',
    projectId: 'signin-3d778',
    storageBucket: 'signin-3d778.firebasestorage.app',
    iosBundleId: 'com.example.googlesignin',
  );
}